spring:
  profiles:
    active: local
  config:
    name: ucsal-tcc

---
spring:
  config:
    activate:
      on-profile: heroku
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
debug: true


---
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
debug: true
